In [1]:
import pandas as pd
import os

In [3]:
bus01_df = pd.read_csv('./data/transit_dfs/BUS01_df.csv', low_memory=False, header=1)
bus01_df.head(10)

,Timestamp_UTC,Latitude_ddeg,Longitude_ddeg,Elevation_m,GPS_Speed_m/s,GPS_Direction_deg,GPS_RMC_Valid_binary,Battery_Voltage_volts,Bus_Box_Temperature_degC,Bus_Top_Temperature_degC,...,GPS_Data_Flagged_binary,Time_Tuple,Date,Year,Month,Day_of_Year,Day_of_Month,Minute,Hour,Transit_ID
0,2021-09-28 16:49:10,40.766273,-111.847641,1474.7,-9999.0,-9999.0,-9999.0,12.50,21.34,22.94,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,49,16,BUS01
1,2021-09-28 16:51:50,40.766617,-111.847954,1476.6,-9999.0,-9999.0,-9999.0,12.61,21.37,23.01,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,51,16,BUS01
2,2021-09-28 16:54:20,40.766483,-111.847748,1474.8,-9999.0,-9999.0,-9999.0,12.30,21.40,23.14,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,54,16,BUS01
3,2021-09-28 16:57:20,40.765793,-111.847237,1473.9,-9999.0,-9999.0,-9999.0,12.58,21.42,23.21,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,57,16,BUS01
4,2021-09-28 16:59:50,40.766312,-111.847649,1476.7,-9999.0,-9999.0,-9999.0,12.57,21.48,23.35,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,59,16,BUS01
5,2021-09-28 17:02:20,40.766411,-111.847694,1478.4,-9999.0,-9999.0,-9999.0,12.31,21.48,23.35,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,2,17,BUS01
6,2021-09-28 17:05:50,40.766304,-111.847603,1482.7,-9999.0,-9999.0,-9999.0,12.34,21.51,23.41,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,5,17,BUS01
7,2021-09-28 17:08:20,40.766232,-111.847618,1478.7,-9999.0,-9999.0,-9999.0,12.35,21.53,23.45,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,8,17,BUS01
8,2021-09-28 17:10:55,40.766422,-111.847282,1472.5,-9999.0,-9999.0,-9999.0,12.61,21.56,23.58,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,10,17,BUS01
9,2021-09-28 17:14:35,40.766361,-111.847855,1470.4,-9999.0,-9999.0,-9999.0,12.37,21.59,23.62,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,14,17,BUS01

In [5]:
grouped_df = bus01_df.groupby(['Latitude_ddeg', 'Longitude_ddeg'])
grouped_df.head(10)

,Timestamp_UTC,Latitude_ddeg,Longitude_ddeg,Elevation_m,GPS_Speed_m/s,GPS_Direction_deg,GPS_RMC_Valid_binary,Battery_Voltage_volts,Bus_Box_Temperature_degC,Bus_Top_Temperature_degC,...,GPS_Data_Flagged_binary,Time_Tuple,Date,Year,Month,Day_of_Year,Day_of_Month,Minute,Hour,Transit_ID
0,2021-09-28 16:49:10,40.766273,-111.847641,1474.7,-9999.0,-9999.0,-9999.0,12.50,21.34,22.94,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,49,16,BUS01
1,2021-09-28 16:51:50,40.766617,-111.847954,1476.6,-9999.0,-9999.0,-9999.0,12.61,21.37,23.01,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,51,16,BUS01
2,2021-09-28 16:54:20,40.766483,-111.847748,1474.8,-9999.0,-9999.0,-9999.0,12.30,21.40,23.14,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,54,16,BUS01
3,2021-09-28 16:57:20,40.765793,-111.847237,1473.9,-9999.0,-9999.0,-9999.0,12.58,21.42,23.21,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,57,16,BUS01
4,2021-09-28 16:59:50,40.766312,-111.847649,1476.7,-9999.0,-9999.0,-9999.0,12.57,21.48,23.35,...,0,"time.struct_time(tm_year=2021, tm_mon=9, tm_md...",2021-09-28,2021,9,271,28,59,16,BUS01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127881,2023-09-26 17:44:10,40.762695,-111.910759,1275.6,0.0,248.2,1.0,13.60,24.92,21.30,...,1,"time.struct_time(tm_year=2023, tm_mon=9, tm_md...",2023-09-26,2023,9,269,26,44,17,BUS01
127882,2023-09-26 17:46:40,40.762737,-111.910744,1276.4,0.0,248.2,1.0,13.61,25.03,21.33,...,1,"time.struct_time(tm_year=2023, tm_mon=9, tm_md...",2023-09-26,2023,9,269,26,46,17,BUS01
127883,2023-09-26 17:49:10,40.762737,-111.910660,1277.5,0.0,117.8,1.0,13.60,25.13,21.33,...,1,"time.struct_time(tm_year=2023, tm_mon=9, tm_md...",2023-09-26,2023,9,269,26,49,17,BUS01
127884,2023-09-26 17:51:40,40.762981,-111.910774,1277.7,0.0,117.8,1.0,13.61,25.22,21.33,...,1,"time.struct_time(tm_year=2023, tm_mon=9, tm_md...",2023-09-26,2023,9,269,26,51,17,BUS01
127885,2023-09-26 17:54:10,40.762764,-111.910698,1276.8,0.0,117.8,1.0,13.61,25.30,21.35,...,1,"time.struct_time(tm_year=2023, tm_mon=9, tm_md...",2023-09-26,2023,9,269,26,54,17,BUS01